name: smart_events_handler
description: Package for handling in easy way deeplink login in the application.
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  meta: ^1.11.0
  provider: ^6.1.2
  rxdart: ^0.27.7

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^11.0.0
  test: ^1.24.0
