name: prepare

on:
  pull_request:
    branches: main

jobs:
  prepare-flutter:
    name: Flutter ${{ matrix.flutter-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ["3.19.x"]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}

      - name: Run analyzer
        run: |
          flutter analyze --no-fatal-infos
          dart run custom_lint

      - name: Run tests
        run: flutter test

      - name: dart format
        run: dart format --set-exit-if-changed .

      - name: Dry run pub publish
        # don't fail the CI, just see how `pub publish` would behave
        run: dart pub publish --dry-run || true
